import {EslintMetadata} from '@src/eslint/models';
import {NODE_VERSION} from '@src/versions';

export const eslintN: EslintMetadata = {
  plugin: {name: 'n', importName: 'n', module: 'eslint-plugin-n'},
  dependencies: {
    'eslint-plugin-n': '17.10.x',
  },
  settings: {
    'node/parsers': {
      '@typescript-eslint/parser': ['.ts', '.tsx'],
    },
    'node/extensions': ['.ts', '.tsx'],
    'node/resolver': {
      typescript: {
        project: './tsconfig.json',
      },
    },
  },
  allOff: {
    'n/callback-return': 'off',
    'n/exports-style': 'off',
    'n/file-extension-in-import': 'off',
    'n/global-require': 'off',
    'n/handle-callback-err': 'off',
    'n/hashbang': 'off',
    'n/no-callback-literal': 'off',
    'n/no-deprecated-api': 'off',
    'n/no-exports-assign': 'off',
    'n/no-extraneous-import': 'off',
    'n/no-extraneous-require': 'off',
    'n/no-missing-import': 'off',
    'n/no-missing-require': 'off',
    'n/no-mixed-requires': 'off',
    'n/no-new-require': 'off',
    'n/no-path-concat': 'off',
    'n/no-process-env': 'off',
    'n/no-process-exit': 'off',
    'n/no-restricted-import': 'off',
    'n/no-restricted-require': 'off',
    'n/no-sync': 'off',
    'n/no-unpublished-bin': 'off',
    'n/no-unpublished-import': 'off',
    'n/no-unpublished-require': 'off',
    'n/no-unsupported-features/es-builtins': 'off',
    'n/no-unsupported-features/es-syntax': 'off',
    'n/no-unsupported-features/node-builtins': 'off',
    'n/prefer-global/buffer': 'off',
    'n/prefer-global/console': 'off',
    'n/prefer-global/process': 'off',
    'n/prefer-global/text-decoder': 'off',
    'n/prefer-global/url': 'off',
    'n/prefer-global/url-search-params': 'off',
    'n/prefer-node-protocol': 'off',
    'n/prefer-promises/dns': 'off',
    'n/prefer-promises/fs': 'off',
    'n/process-exit-as-throw': 'off',
  },
  onlyOn: {
    'n/callback-return': ['warn', ['callback', 'cb', 'next', 'done']],
    'n/file-extension-in-import': ['warn', 'never'],
    'n/global-require': 'warn',
    'n/handle-callback-err': ['warn', '^(err|error)$'],
    'n/hashbang': 'warn',
    'n/no-deprecated-api': 'warn',
    'n/no-exports-assign': 'warn',
    'n/no-extraneous-import': 'warn',
    'n/no-new-require': 'warn',
    'n/no-path-concat': 'warn',
    'n/no-process-env': 'warn',
    'n/no-process-exit': 'warn',
    'n/no-sync': 'warn',
    'n/no-unsupported-features/es-builtins': ['warn', {version: NODE_VERSION}],
    'n/no-unsupported-features/es-syntax': ['warn', {version: NODE_VERSION}],
    'n/no-unsupported-features/node-builtins': ['warn', {version: NODE_VERSION}],
    'n/prefer-global/buffer': ['warn', 'always'],
    'n/prefer-global/console': ['warn', 'always'],
    'n/prefer-global/process': ['warn', 'always'],
    'n/prefer-global/text-decoder': ['warn', 'always'],
    'n/prefer-global/url': ['warn', 'always'],
    'n/prefer-global/url-search-params': ['warn', 'always'],
    'n/prefer-node-protocol': 'warn',
    'n/prefer-promises/dns': 'warn',
    'n/prefer-promises/fs': 'warn',
    'n/process-exit-as-throw': 'warn',
  },
};
