import {EslintMetadata} from '../models';

/* eslint-disable @typescript-eslint/naming-convention */
export const eslintNode: EslintMetadata = {
  plugin: ['node'],
  dependencies: {
    'eslint-plugin-node': '11.1.x',
  },
  settings: {},
  allOff: {
    'node/callback-return': 'off',
    'node/exports-style': 'off',
    'node/file-extension-in-import': 'off',
    'node/global-require': 'off',
    'node/handle-callback-err': 'off',
    'node/no-callback-literal': 'off',
    'node/no-deprecated-api': 'off',
    'node/no-exports-assign': 'off',
    'node/no-missing-import': 'off',
    'node/no-missing-require': 'off',
    'node/no-mixed-requires': 'off',
    'node/no-new-require': 'off',
    'node/no-path-concat': 'off',
    'node/no-process-env': 'off',
    'node/no-process-exit': 'off',
    'node/no-restricted-import': 'off',
    'node/no-restricted-require': 'off',
    'node/no-sync': 'off',
    'node/no-unpublished-bin': 'off',
    'node/no-unpublished-import': 'off',
    'node/no-unpublished-require': 'off',
    'node/no-unsupported-features/es-builtins': 'off',
    'node/no-unsupported-features/es-syntax': 'off',
    'node/no-unsupported-features/node-builtins': 'off',
    'node/prefer-global/buffer': 'off',
    'node/prefer-global/console': 'off',
    'node/prefer-global/process': 'off',
    'node/prefer-global/text-decoder': 'off',
    'node/prefer-global/text-encoder': 'off',
    'node/prefer-global/url-search-params': 'off',
    'node/prefer-global/url': 'off',
    'node/prefer-promises/dns': 'off',
    'node/prefer-promises/fs': 'off',
    'node/process-exit-as-throw': 'off',
    'node/shebang': 'off',
  },
  onlyOn: {
    'node/callback-return': ['warn', ['callback', 'cb', 'next', 'done']],
    'node/file-extension-in-import': ['warn', 'never'],
    'node/global-require': 'warn',
    'node/handle-callback-err': 'warn',
    'node/no-deprecated-api': 'warn',
    'node/no-exports-assign': 'warn',
    'node/no-mixed-requires': 'warn',
    'node/no-new-require': 'warn',
    'node/no-path-concat': 'warn',
    'node/no-process-env': 'warn',
    'node/no-process-exit': 'warn',
    'node/no-sync': 'warn',
    'node/no-unsupported-features/es-builtins': ['warn', {version: '>=14'}],
    'node/no-unsupported-features/es-syntax': ['warn', {version: '>=14', ignores: ['modules']}],
    'node/no-unsupported-features/node-builtins': ['warn', {version: '>=14'}],
    'node/prefer-global/buffer': ['warn', 'always'],
    'node/prefer-global/console': ['warn', 'always'],
    'node/prefer-global/process': ['warn', 'always'],
    'node/prefer-global/text-decoder': ['warn', 'always'],
    'node/prefer-global/url-search-params': ['warn', 'always'],
    'node/prefer-promises/dns': 'warn',
    'node/prefer-promises/fs': 'warn',
    'node/process-exit-as-throw': 'warn',
  },
};
/* eslint-enable @typescript-eslint/naming-convention, no-null/no-null */
