import {EslintMetadata} from '../models';

export const eslintImport: EslintMetadata = {
  plugin: ['import'],
  dependencies: {
    'eslint-plugin-import': '2.24.x',
    'eslint-import-resolver-typescript': '2.5.x',
  },
  settings: {
    'import/parsers': {
      '@typescript-eslint/parser': ['.ts', '.tsx'],
    },
    'import/extensions': ['.ts', '.tsx'],
    'import/resolver': {
      node: {
        extensions: ['.js', '.jsx', '.ts', '.tsx'],
      },
    },
  },
  allOff: {
    'import/default': 'off',
    'import/dynamic-import-chunkname': 'off',
    'import/export': 'off',
    'import/exports-last': 'off',
    'import/extensions': 'off',
    'import/first': 'off',
    'import/group-exports': 'off',
    'import/max-dependencies': 'off',
    'import/named': 'off',
    'import/namespace': 'off',
    'import/newline-after-import': 'off',
    'import/no-absolute-path': 'off',
    'import/no-amd': 'off',
    'import/no-anonymous-default-export': 'off',
    'import/no-commonjs': 'off',
    'import/no-cycle': 'off',
    'import/no-default-export': 'off',
    'import/no-deprecated': 'off',
    // use @typescript-eslint/no-duplicate-imports
    'import/no-duplicates': 'off',
    'import/no-dynamic-require': 'off',
    'import/no-extraneous-dependencies': 'off',
    'import/no-internal-modules': 'off',
    'import/no-import-module-exports': 'off',
    'import/no-mutable-exports': 'off',
    'import/no-named-as-default-member': 'off',
    'import/no-named-as-default': 'off',
    'import/no-named-default': 'off',
    'import/no-named-export': 'off',
    'import/no-namespace': 'off',
    'import/no-nodejs-modules': 'off',
    'import/no-relative-packages': 'off',
    'import/no-relative-parent-imports': 'off',
    'import/no-restricted-paths': 'off',
    'import/no-self-import': 'off',
    'import/no-unassigned-import': 'off',
    'import/no-unresolved': 'off',
    'import/no-unused-modules': 'off',
    'import/no-useless-path-segments': 'off',
    'import/no-webpack-loader-syntax': 'off',
    // use simple-import-sort/sort
    'import/order': 'off',
    'import/prefer-default-export': 'off',
    'import/unambiguous': 'off',
  },
  onlyOn: {
    'import/default': 'warn',
    'import/dynamic-import-chunkname': 'warn',
    'import/export': 'warn',
    'import/first': 'warn',
    'import/no-amd': 'warn',
    'import/no-anonymous-default-export': 'warn',
    'import/no-default-export': 'warn',
    'import/no-deprecated': 'warn',
    'import/no-import-module-exports': 'warn',
    'import/no-mutable-exports': 'warn',
    'import/no-named-as-default-member': 'warn',
    'import/no-named-as-default': 'warn',
    'import/no-named-default': 'warn',
    'import/no-namespace': 'warn',
    'import/no-relative-packages': 'warn',
    'import/no-self-import': 'warn',
    'import/no-unassigned-import': 'warn',
    'import/no-unresolved': 'warn',
    'import/no-useless-path-segments': 'warn',
    'import/no-webpack-loader-syntax': 'warn',
  },
};
